[general]
debug = false
cursor = "_"
show_cursor = true
blink_cursor = true
user_name = "x0rzavi" # for prompt
fps = 15
color_scheme = "yoru"
loop_count = 0 # infinite loop

[files]
frame_base_name = "frame_"
frame_folder_name = "frames"
output_gif_name = "output"
